const PrivacyData = () => {

  const privacyPolicyData = [
    {
      title: "Introduction",
      description: "This Privacy Policy outlines how ShortNotice ('we,' 'us,' or 'our') collects, uses, shares, and protects user data. By using ShortNotice, you agree to the practices described in this policy."
    },
    {
      title: "Data Collection",
      description:
        <div>
          We collect the following data:
          <ul className='list-unstyled'>
            <li>
              - Email Account Information: The email address provided during account creation is stored securely in our database (via Appwrite). It may also be saved locally in your browser's local storage, along with the unique user ID generated by Appwrite. This enables features such as keeping you signed in and improving overall user experience.
            </li>
            <li>
              - Name: The name you provide during sign-up is stored securely in our database (via Appwrite) for account management purposes. It is not displayed publicly on the platform.
            </li>
            <li>
              - Username: The username you choose is stored and may be visible to other users on the platform.
            </li>
            <li>
              - Content Shared: Any text, images, or other media shared by users on the platform.
            </li>
            <li>
              - Uploaded Files: Avatars and other files uploaded by users are stored in Appwrite with their original filenames as provided by the user's device. These filenames may contain personal or identifying information.
            </li>
            <li>
              - Technical Data: IP address and usage logs collected by Appwrite on behalf of ShortNotice. This data is accessible to ShortNotice through Appwrite and is primarily used for debugging and maintaining platform security.
            </li>
          </ul>
        </div>
    },
    {
      title: "Data Usage",
      description:
        <div>
          The data we collect is used to:
          <ul className='list-unstyled'>
            <li>- Facilitate account creation.</li>
            <li>- Display content and enable interactions within the platform.</li>
            <li>- Moderate and enforce our Terms of Service and Community Guidelines.</li>
            <li>- Improve platform functionality and user experience.</li>
          </ul>
        </div>
    },
    {
      title: "Data Sharing",
      description:
        <div>
          ShortNotice does not sell or rent user data to third parties. However, data may be shared in the following instances:
          <ul className='list-unstyled'>
            <li>- Service Providers: We rely on Appwrite to provide backend infrastructure and database services. Appwrite processes and stores user data (including IP addresses) on our behalf. Your data is stored securely within Appwrite's infrastructure.</li>
            <li>- Legal Requirements: If required by law, we may disclose user data to comply with legal processes.</li>
            <li>- Platform Integrity: In cases of reported content or account violations, data may be reviewed internally for resolution.</li>
          </ul>
        </div>
    },
    {
      title: "Data Storage and Security",
      description:
        <div>
          Your data is stored on servers managed by Appwrite. While we strive to protect your information, ShortNotice is a personal project and does not implement advanced security measures such as end-to-end encryption or multi-factor authentication. Users are encouraged to:
          <ul className='list-unstyled'>
            <li>- Use strong passwords for their accounts.</li>
            <li>- Avoid sharing sensitive or personal information on the platform. </li>
          </ul>
        </div>
    },
    {
      title: "User Rights",
      description:
        <div>
          Users have the right to:
          <ul className='list-unstyled'>
            <li>- Request access to the data we store about them.</li>
            <li>- Request correction or deletion of their data.</li>
            <li>- Report privacy violations using the 'Privacy Violation' category in the Community Guidelines.</li>
          </ul>
        </div>
    },
    {
      title: "Cookies and Tracking",
      description: `
      ShortNotice may use cookies, local storage, or similar technologies to enhance functionality. These are used solely for session management and do not track users outside the platform.
    `
    },
    {
      title: "Children\'s Privacy",
      description: `
      ShortNotice is not intended for users under the age of 18. We do not knowingly collect personal data from children. If we become aware that such data has been collected, we will delete it promptly.
    `
    },
    {
      title: "Updates to This Policy",
      description: `
      This Privacy Policy may be updated periodically. Users will be notified of changes through platform announcements. Continued use of ShortNotice after updates constitutes acceptance of the revised policy.
    `
    },
    {
      title: "Contact Information",
      description: `
      For questions or concerns about this Privacy Policy, please contact us at: shortnotice@altmails.com.
    `
    }
  ];

  return { privacyPolicyData };
}

export default PrivacyData;

